language: java
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    - maksimilian.koturanov@gmail.com

install: ignore

script: mvn clean verify -Pintegration_test -Djdbc.properties=test-jdbc-connection

after_success:
  - bash <(curl -s https://codecov.io/bash)